version: '3.8'

services:
  snmp-alert:
    build: .
    container_name: snmp-alert
    restart: always
    env_file:
      - .env
    ports:
      - "162:162/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./configs:/app/configs
      - ./output:/app/output
